# Generated by Django 2.1.7 on 2019-03-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Credit_attemp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='Credit_passed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='aam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='wam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='attend_mode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizen_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizen_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_type_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_ini',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_per',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_enrol_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='level',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='semester',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
